DROP TABLE IF EXISTS url;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shortcut TEXT UNIQUE NOT NULL,
  original TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
